name: pr-validation-wf

on:
  pull_request:
  types:
  - opened
  - closed
jobs:
pr-validation-wf:
    runs-on: ubuntu-latest
    steps:
      - name: welcome steps
        run: echo "welcome to github"

 

